config/routes.rb
Rails.application.routes.draw do
  get 'followers/index'
  devise_for :users

  root to: 'pages#index'

  scope :profiles do
    post 'index', to: "profiles#index", as: 'profiles_index'
    post ':id/follow', to: "profiles#follow", as: "follow"
    post ':id/unfollow', to: "profiles#unfollow", as: "unfollow"
    get ':id/show', to: "profiles#show", as: "profile"
  end
  resources :followers, only: :index

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: :create
  end

  resources :pages
  get '/search', to: "pages#search", as: "search"


  resources :topics, only: [:index, :new, :create, :show] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:edit, :update, :destroy]
  resources :topics, only: [:edit, :update, :destroy]

  post "add-like-topic/:id", to: 'topics#add_topic_like', as: "like_topic"

  # post "add-like-post/:post_id", to: 'posts#add_post_like', as: "like_post"

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :topic_likes, dependent: :destroy
  paginates_per 8

  include PgSearch::Model
  multisearchable against: [:title, :content]

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_counter, only: [:show]
  before_action :set_topics, only: [:show, :edit, :update, :destroy, :add_topic_like]
  skip_before_action :verify_authenticity_token, :only => [:add_topic_like]

  def index
  end

  def new
    @topic = Topic.new
  end

  def show
    @topic_like = !@topic.topic_likes.where(user_id: current_user.id).first.nil?
    respond_to do |format|
        format.html
        format.json { render json: { counter: @topic_likes_counter, liked: @topic_like } }
      end
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to pages_path, notice: 'Topic was successfully erased!'
  end

  def add_topic_like
    topic_like = @topic.topic_likes.where(user_id: current_user.id).first
    if topic_like.nil?
      @topic.like_count +=1
      TopicLike.create(topic: @topic, user: current_user)
    else
      @topic.like_count -=1
      topic_like.destroy
    end
    @topic.save
    respond_to do |format|
          format.html
          format.json { render json: { counter: @topic.like_count, liked: !topic_like.nil? } }
        end
  end

  def search
    if params[:query].present?
      @results = PgSearch.multisearch(params[:query])
    else
      @results = Topic.all
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :content)
  end

  def set_topics
    @topic = Topic.find(params[:id])
  end

  def set_counter
    set_topics
    @topic_likes_counter = @topic.like_count
  end
end

app/views/topics/edit.html.erb
<div class="container">
  <h1>Editar Post</h1>

  <%= simple_form_for @topic do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/topics/new.html.erb
<!-- página para criar novo tópico -->
<div class="container">
  <h1>New Topic</h1>

  <%= simple_form_for @topic do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/topics/show.html.erb
<!-- Aqui os posts serão inseridos por tópico -->
<div class="container">
  <div>

    <h4><%= @topic.title %> </h4>
      <%= link_to page_path(@topic.user_id) do%>
        <%= cl_image_tag @topic.user.photo.key, class: "avatar" %>
        <p> Criado por <strong><%= @topic.user.first_name %></strong> </p>
      <%end%>
      <p> <%= @topic.content %>
        <% if current_user.id == @topic.user_id %>
          <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_topic_path(@topic) %> -
          <%= link_to  '<i class="far fa-trash-alt"></i>'.html_safe, @topic, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <div id='topic_counter' data-controller="topic" class="like-button">
          <span class="d-none" data-target="topic.topicId"> <%= @topic.id %></span>
          <p data-target="topic.counter" style="margin-right: 5px;" > <%= @topic.like_count %> </p>
          <%= link_to "#", remote: true, data: {target: "topic.button" } do  %>
             <i class="far fa-heart" data-action="click->topic#refresh" ></i>
          <% end %>
        </div>
      </p>
  </div>
  <div>
    <h5>Comentários</h5>
    <div>
      <% @topic.posts.each do |post|%>

        <div class="card-post" style= "">
            <p> <strong> <%= post.user.first_name %> </strong>- <%= post.content %>
              <% if current_user.id == post.user.id %>
              <div class="icons">
                <div>
                  <p> <%#= post.like_count %> <%#= link_to '<i class="fas fa-thumbs-up"></i>'.html_safe, like_post_path(post), remote: true, method: :post %> </p>
                </div>
                <div>
                  <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(post) %> - <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                </div>
              </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
  <div>
    <%= link_to "Comentar", new_topic_post_path(@topic), class: "btn btn-primary mt-5" %>
  </div>
</div>