config/routes.rb
Rails.application.routes.draw do
  get 'followers/index'
  devise_for :users

  root to: 'pages#index'

  scope :profiles do
    post 'index', to: "profiles#index", as: 'profiles_index'
    post ':id/follow', to: "profiles#follow", as: "follow"
    post ':id/unfollow', to: "profiles#unfollow", as: "unfollow"
    get ':id/show', to: "profiles#show", as: "profile"
  end
  resources :followers, only: :index

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: :create
  end

  resources :pages
  get '/search', to: "pages#search", as: "search"


  resources :topics, only: [:index, :new, :create, :show] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:edit, :update, :destroy]
  resources :topics, only: [:edit, :update, :destroy]

  post "add-like-topic/:id", to: 'topics#add_topic_like', as: "like_topic"

  # post "add-like-post/:post_id", to: 'posts#add_post_like', as: "like_post"

end

app/views/shared/_chatrooms.html.erb
<div class="container">
  <div class="chat-box">
    <div class="row">
    <h4>Minhas mensagens</h4>
      <% my_chatrooms.each do |chatroom| %>
        <ul class="list-group">
          <li class="list-group-item ">
            <i class="fas fa-comment-dots" ></i>
            <%= link_to "Chat com #{chatroom.user.first_name}", chatroom_path(chatroom) %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_followers.html.erb
<div class="container">
  <%= link_to followers_path do %>
    <h6 id="followers-title">Seguidores</h6>
  <% end  %>
  <div class="followings">
    <% followers.each do |follower| %>
    <div class="following-card">
      <div class="following-pic">
        <%= link_to page_path(follower) do%>
          <%= cl_image_tag follower.photo.key, height: '50px', class: 'avatar' %>
      </div>
      <div class="following-name">
      </div>
      <% end  %>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_followings.html.erb
<div class="container">
  <%= link_to followers_path do %>
    <h6 id="title1-right-box">Seguindo</h6>
  <% end  %>
  <div class="followings">
    <% followings.each do |following| %>
    <div class="following-card">
      <div class="following-pic">
      <%= link_to page_path(following) do%>
        <%= cl_image_tag following.photo.key, height: '50px', class: 'avatar' %>
      </div>
      <div class="following-name">
      </div>
      <% end  %>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links slogan">
    <a href="https://www.who.int/" target="_blank" class="slogan" ><i class="fas fa-globe"></i></a>
    <p>Acesse Organização Mundial de Saúde</p>
  </div>
  <div class="slogan">

  </div>
  <div class="footer-copyright">
    <p> R@ros! </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="logo">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'trevo_01.png', width: '30px', height: '30px', color: 'pink' %>
  <% end %>
  <h1 class="mt-3" >Raros</h1>
</div>

  <div class="d-flex align-items-center mr-5" >
  <%= form_tag search_path, method: :get, class: "search" do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Buscar"
    %>

    <%= button_tag :submit, class: "btn-style" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: '100%', height: '40px' %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Editar", edit_user_registration_path, class: "dropdown-item" %>
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
.search-results {}

app/views/shared/_topics.html.erb
<div class="topics" >
  <div><h1>Atividade</h1></div>
    <% topics.each do |t| %>
      <div class="card">
    <%= link_to topic_path(t) do %>
        <div style="display: flex;">
          <%= cl_image_tag t.user.photo.key, class: "avatar" %>
          <h5 style="margin-left: 10px; "><strong> <%= t.user.first_name %></strong> </h5>
        </div>
        <p style="font-size: 11px"> <%= time_ago_in_words t.created_at %> </p>
        <h6> <%= link_to t.title, topic_path(t) %> </h6>
        <p> <%= t.content.truncate(200, separator: ' ') %> </p>
      <% end %>
      </div>
    <% end %>
</div>