config/routes.rb
Rails.application.routes.draw do
  get 'followers/index'
  devise_for :users

  root to: 'pages#index'

  scope :profiles do
    post 'index', to: "profiles#index", as: 'profiles_index'
    post ':id/follow', to: "profiles#follow", as: "follow"
    post ':id/unfollow', to: "profiles#unfollow", as: "unfollow"
    get ':id/show', to: "profiles#show", as: "profile"
  end
  resources :followers, only: :index

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: :create
  end

  resources :pages
  get '/search', to: "pages#search", as: "search"


  resources :topics, only: [:index, :new, :create, :show] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:edit, :update, :destroy]
  resources :topics, only: [:edit, :update, :destroy]

  post "add-like-topic/:id", to: 'topics#add_topic_like', as: "like_topic"

  # post "add-like-post/:post_id", to: 'posts#add_post_like', as: "like_post"

end

app/views/pages/_info_window.html.erb
<div class="container">
  <div class="photo">
    <%= cl_image_tag user.photo.key, class: 'avatar' %>
  </div>
  <div class="name">
    <%= user.first_name %>
    <%= user.last_name %>
  </div>
  <div class="disease">
    <%= user.disease.name %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="header">
    <h1>R@ros</h1>
  </div>
  <div class="signin">

  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="container-home">
    <div class="profile-informations">

      <div>
        <%= image_tag 'back-banners.jpg', class: 'background-image-card' %>
      </div>

      <div class="info-card-home">
        <div class="user-photo" >
          <% if current_user%>
            <%= link_to page_path(current_user) do %>
              <%= cl_image_tag current_user.photo.key, width: '100%', height: "250px", class: 'avatar-xlarge' %>
            <% end %>
          <% end %>
        </div>

        <div class="user-name">
          <p>
            <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
          </p>
        </div>


        <div class="age">
          <span class="info-user-line-age" >
            <i class="fas fa-birthday-cake"  style="font-size: 18px"></i>
          </span>
          <%= @age if current_user %> anos
        </div>

        <div class="disease-name">
          <span class="info-user-line-disease"></span>
            <%= image_tag 'clover_transparent.png', width: '20px'%>
          <%= current_user.disease.name.capitalize %>
        </div>
      </div>
    </div>

    <div class="feed-news">
      <div class="new-topic-navbar">
        <div class="home-icone">
          <%= link_to followers_path do %>
            <i class="fas fa-user-friends" style="font-size: 28px"></i>

            <%#= image_tag 'home_transparent.png', width: '29px' %>
          <% end  %>
        </div>
        <div class="post-it">
          <%= link_to new_topic_path, data: {toggle: "modal", target: "#topicModalCenter"} do %>
            <i class="far fa-edit" style="font-size: 28px"></i>
            <%#= image_tag 'edit.png', width: '28px' %>
          <% end %>
          <div class="modal fade" id="topicModalCenter" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <%= simple_form_for Topic.new, remote: true do |f| %>
                  <div class="modal-header">
                    <%= f.input :title, label: false, placeholder: "Título", width: '100%' %>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= f.input :content, label: false, placeholder: "Conteúdo" %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit "Post", class: "btn btn-primary btn-block" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="chat">
          <%= link_to chatrooms_path do %>
            <i class="far fa-comment-dots " style="font-size: 28px"></i>
            <%#= image_tag 'chat.png', width: '25px' %>
          <% end  %>
        </div>

        <i class="far fa-map" style="font-size: 27px" data-toggle="modal" data-target=".bd-example-modal-lg"></i>
         <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
           <div class="modal-dialog modal-lg">
             <div class="modal-content">
               <div id="map"
                 style="width: 60vw; height: 50vh; border-radius: 5px;"
                 data-markers="<%= @markers.to_json %>"
                 data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
               </div>
             </div>
           </div>
         </div>
       </div>
        <div>
          <%= render partial: "shared/topics", locals: { topics: @topics } %>
          <%= paginate @topics, theme: 'twitter-bootstrap-4' %>
       </div>
    </div>
    <div class="more">
      <div class="follows">
        <div class="followings-home">
          <%= render 'shared/followings', followings: current_user.following.last(9) %>
        </div>
        <div class="followers-home">
          <%= render 'shared/followers', followers: current_user.followers.last(9) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<div class="container">

  <% @results.each do |result| %>
    <% a = result.searchable %>
      <% if result[:searchable_type] == 'User' %>
      <h6 class="search-results">Resultado por Raros:</h6>
        <%= link_to page_path(a) do %>
          <div class="search-user-card">
            <div class="info-inside-search">
              <%= cl_image_tag a.photo.key, class: 'avatar-large' %>

              <div class="search-all-info">
                <p style="font-weight:bold"><%= a.first_name %> <%= a.last_name %></p>
                <p><%= a.address %></p>
                <p><%= a.disease.name %></p>
              </div>
            </div>

            <div class="follow-search">
              <% if user_signed_in? && current_user.id != a.id %>
                <% if current_user.is_following?(a.id) %>
                  <button type="button" class="btn btn-primary"><%= link_to "Deixar de seguir", unfollow_path(a.id), method: :post, remote: true %></button>
                <% else %>
                  <button type="button" class="btn btn-primary"><%= link_to "Seguir", follow_path(a.id), method: :post, remote: true  %></button>
                <% end %>
              <% end %>
            </div>

          </div>
        <% end %>
      <% elsif result[:searchable_type] == 'Topic'%>
      <h6 class="search-results">Resultado por tópicos:</h6>
        <div class="search-post">
          <div class="search-post-title">
            <strong><%= a.title %></strong>
          </div>
          <div class="search-like">
            <div class="search-content">
              <%= a.content %>
            </div>
            <div class="search-menu-topic">
              <% if current_user.id == a.user_id %>
                <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_topic_path(a) %>
                <%= link_to  '<i class="far fa-trash-alt"></i>'.html_safe, a, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
                <div id='topic_counter' data-controller="topic" class="like-button">
                  <span class="d-none" data-target="topic.topicId"> <%= a.id %></span>
                  <p data-target="topic.counter" style="margin-right: 5px;" > <%= a.like_count %></p>
                    <%= link_to "#", remote: true, data: {target: "topic.button" } do  %>
                    <i class="far fa-heart" data-action="click->topic#refresh" ></i>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
      <% elsif result[:searchable_type] == 'Disease' %>
      <h6 class="search-results">Resultado por raridades:</h6>
        <div class="search-disease-card">
          <p><i class="fas fa-stethoscope fa-2x"></i></p>
          <p style="font-weight:bold"><%= a.name %></p>
          <p style="font-weight:bold"><%= a.cid_10 %></p>
        </div>
        <h6 class="search-results">Raros por raridades:</h6>
        <% a.users.each do |user| %>

          <div class="search-user-card">
            <%= link_to page_path(user) do %>
              <div class="info-inside-search">
                <%= cl_image_tag user.photo.key, class: 'avatar-large' %>
                <div class="search-all-info">
                  <p style="font-weight:bold"><%= user.first_name %> <%= user.last_name %></p>
                  <p ><%= user.address%></p>
                </div>
              </div>
            <%end%>

            <div class="follow-search">
              <% if user_signed_in? && current_user.id != user.id %>
                <% if current_user.is_following?(user.id) %>
                  <button type="button" class="btn btn-primary btn-block"><%= link_to "Deixar de seguir", unfollow_path(user.id), method: :post, remote: true %></button>
                <% else %>
                  <button type="button" class="btn btn-primary btn-block"><%= link_to "Seguir", follow_path(user.id), method: :post, remote: true  %></button>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end%>

      <% else %>
        <div class="no-results">
          <h5>Não foram encontrados dados para sua pesquisa</h5>
        </div>
      <% end %>
  <% end %>

</div>

app/views/pages/show.html.erb
<div class="container">

  <div class="header">
    <div class="profile-pic">
      <%= cl_image_tag @user.photo.key, class: "avatar-x" if @user.photo.attached? %>
    </div>

    <div class="display-name">
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
    </div>
  </div>

  <div class="content">

    <div class="content-block-left">
      <div class="follow">

        <p class="follow-count">Seguidores: <%= @user.followers.count %> </p>
        <p class="follow-count">Seguindo: <%= @user.following.count %></p>


        <% if user_signed_in? && current_user.id != @user.id %>
          <% if current_user.is_following?(@user.id) %>
            <span class="btn btn-primary  btn-block"> <%= link_to "Parar de seguir", unfollow_path(@user.id), method: :post, remote: true %></span>
          <% else %>
            <span class="btn btn-primary btn-block"><%= link_to "Seguir", follow_path(@user.id), method: :post, remote: true %></span>
          <% end %>
          <% end %>
      </div>


      <div class="info">
        <h4>Sobre mim</h4>
        <p> <%= @user.description %></p>
        <p><i class="fas fa-birthday-cake" style="font-size: 19px"></i>  Idade: <%= @age  %> anos</p>
        <p><%= image_tag 'clover_transparent.png', width: '20px'%> Raridade: <%= @user.disease.name %></p>
          <% if @user != current_user %>
            <p class="btn btn-primary btn-block"><i class="far fa-comments"></i> <%= link_to "Diga oi!", chatrooms_path(id: @user.id), method: :post %></p>
          <% end %>
          <% if @user == current_user %>
            <p class="btn btn-primary btn-block"><%= link_to "Editar", edit_user_registration_path %></p>
          <% end %>
      </div>
    </div>

    <div class="middle-col">



      <% if @user == current_user %>
        <div class="container-post">
          <%= cl_image_tag @user.photo.key, class: "avatar-large pic-post" %>
          <span class= "post-create btn-block">
          <%= link_to "O que você gostaria de dizer hoje?", new_topic_path, data: {toggle: "modal", target: "#topicModalCenter"} %>
            <div class="modal fade" id="topicModalCenter" tabindex="-1" role="dialog">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <%= simple_form_for Topic.new, remote: true do |f| %>
                    <div class="modal-header">
                      <%= f.input :title, label: false, placeholder: "Título do post" %>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= f.input :content, label: false, placeholder: "Compartilhe sentimentos e dúvidas com outros Raros." %>
                    </div>
                    <div class="modal-footer">
                      <%= f.submit "Publicar", class: "btn btn-primary btn-block" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </span>
        </div>
      <% end %>

      <div class="post-list">
        <h4>Últimos posts</h4>
          <% if @topics.count == 0 %>
            <span class="no-post"> Ops! Parece que <%= @user.first_name %> ainda não escreveu nada por aqui. </span>
          <% else %>
            <ul class="items">
            <% @topics.last(5).each do |topic| %>
              <li style="margin-top: 20px" >
                <%= cl_image_tag @user.photo.key, class: "avatar" %>
                <%= link_to topic.title, topic_path(topic) %>
              </li>
            <% end %>
            </ul>
          <%end%>
      </div>
    </div>
  </div>
</div>